apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: store-database-deployment
  labels:
    app: store-database-deployment
spec:
  selector:
    matchLabels:
      app: store-database-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: store-database-deployment
    spec:
      containers:
        # - image: mysql:5.7
        - image: mariadb:10.4.17
          name: store-database-deployment
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: sealteam
            - name: MYSQL_PASSWORD
              value: sckshuhari
            - name: MYSQL_DATABASE
              value: toy
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            tcpSocket:
              port: 3306
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
