apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-loadbalancer
  labels:
    app: store-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-loadbalancer
  template:
    metadata:
      labels:
        app: store-loadbalancer
    spec:
      containers:
        # - image: sckseal/toy-store-nginx:0.0.1
        - image: jengweb/toy-store-nginx:1.0.0
          name: store-loadbalancer
          ports:
            - containerPort: 80
