apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  type: NodePort
  selector:
    app: store-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32300
