apiVersion: v1
kind: Service
metadata:
  name: store-web
spec: 
  type: NodePort
  selector:
    app: store-web
  ports: 
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
    